module Submit64
  class Submit64Exception < StandardError
    attr_accessor http_status: Integer

    def initialize: (String, Integer) -> Submit64Exception
    def self.new_raw: (String, Integer) -> Submit64Exception

  end
end
