use Submit64::MetadataProvider::*

module Submit64
  VERSION: String

  type get_generic = {
      resourceName: String,
    } & Hash[String, untyped]

  self.@current_user: instance | nil
  self.@settings: {
      always_exclude: Array[Symbol]
    }

  def self.get_metadata_and_data: ({
      submit64Params: get_metadata_params
    }) -> get_metadata_params_response

  def self.get_association_data: ({
      submit64Params: get_association_data
    }) -> get_association_data_response

  def self.submit_form: ({
      submit64Params: get_submit_data
    }) -> get_submit_data_response

  def self.permit_metadata_and_data_params: (instance) -> instance

  def self.permit_association_data_params: (instance) -> instance

  def self.permit_submit_params: (instance) -> instance

  def self.get_association_data_pagination_limit: -> Integer

  def self.ensure_params_and_resource_are_valid: (get_generic) -> instance

  private

  def self.safe_exec: [T] () { () -> T } -> T

end
