use Submit64::MetadataProvider::*

module Submit64
  VERSION: String

  self.@current_user: Class | nil
  self.@settings: {
      always_exclude: Array[Symbol]
    }

  def self.get_metadata_and_data: ({
      submit64Params: get_metadata_params
    }) -> get_metadata_params_response

  def self.get_association_data: ({
      submit64Params: get_association_data
    }) -> get_association_data_response

  def self.submit_form: ({
      submit64Params: get_submit_data
    }) -> get_submit_data_response

  def self.permit_metadata_and_data_params: (Class) -> Class

  def self.permit_association_data_params: (Class) -> Class

  def self.permit_submit_params: (Class) -> Class

  def self.get_association_data_pagination_limit: -> Integer
end
